# Default values for probot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: node
  tag: alpine
  pullPolicy: IfNotPresent

git:
  registry: docker.io
  repository: bitnami/git
  tag: 2.23.0-debian-9-r3
  pullPolicy: IfNotPresent

repository:  https://github.com/paschdan/probot-assignee.git

## Specify the number of replicas for the application
##
replicaCount: 1

## Specify the port where your application will be running
##
applicationPort: 3000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: probot.k8s
      paths: 
      - '/'

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
